#!/usr/bin/env node

/**
 * TerraMind Core — Interactive Setup Script
 * 
 * One-line install:
 *   git clone https://github.com/masood1996-geo/terramind-core.git && cd terramind-core && node setup.js
 * 
 * This script:
 * 1. Prompts for optional API keys (with direct links to get them)
 * 2. Creates the .env file
 * 3. Installs dependencies
 * 4. Starts the development server
 */

const { createInterface } = require('readline');
const { writeFileSync, existsSync } = require('fs');
const { execSync } = require('child_process');

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((resolve) => rl.question(q, resolve));

const C = '\x1b[36m';   // cyan
const G = '\x1b[32m';   // green
const Y = '\x1b[33m';   // yellow
const R = '\x1b[31m';   // red
const D = '\x1b[2m';    // dim
const B = '\x1b[1m';    // bold
const X = '\x1b[0m';    // reset

function banner() {
  console.log('');
  console.log(`${C}${B}  ╔══════════════════════════════════════════════════════════╗${X}`);
  console.log(`${C}${B}  ║                                                          ║${X}`);
  console.log(`${C}${B}  ║   🌍  TerraMind Core v4.0 — Setup Wizard                ║${X}`);
  console.log(`${C}${B}  ║   Global Disaster Intelligence Platform                  ║${X}`);
  console.log(`${C}${B}  ║                                                          ║${X}`);
  console.log(`${C}${B}  ╚══════════════════════════════════════════════════════════╝${X}`);
  console.log('');
}

function section(title) {
  const pad = Math.max(2, 52 - title.length);
  console.log('');
  console.log(`${B}  ── ${title} ${'─'.repeat(pad)}${X}`);
  console.log('');
}

async function main() {
  banner();

  console.log(`  TerraMind aggregates real-time disaster data from 4 government sources:`);
  console.log(`  ${D}• USGS Earthquakes         (no key needed)${X}`);
  console.log(`  ${D}• NASA EONET Wildfires      (no key needed)${X}`);
  console.log(`  ${D}• NOAA Weather Alerts       (no key needed)${X}`);
  console.log(`  ${G}• NASA FIRMS Fire Detection  (free key — optional)${X}`);
  console.log(`  ${G}• AI GeoScience Chat         (free key — optional)${X}`);
  console.log('');
  console.log(`  ${D}The platform works without any API keys. Keys unlock extra features.${X}`);

  // ── Check for existing .env ──
  if (existsSync('.env')) {
    console.log('');
    const overwrite = await ask(`  ${Y}⚠  A .env file already exists. Overwrite? (y/N): ${X}`);
    if (overwrite.toLowerCase() !== 'y') {
      console.log(`  ${D}Keeping existing .env file.${X}`);
      await installAndStart();
      rl.close();
      return;
    }
  }

  // ── NASA FIRMS API Key ──
  section('1/3  NASA FIRMS — Satellite Fire Detection');
  console.log(`  FIRMS provides global satellite fire detections from VIIRS (375m resolution).`);
  console.log(`  Without this key, fire detection is ${Y}disabled${X} — all other sources still work.`);
  console.log('');
  console.log(`  ${C}${B}Get your free key here (takes 30 seconds):${X}`);
  console.log(`  ${B}→ https://firms.modaps.eosdis.nasa.gov/api/area/${X}`);
  console.log(`  ${D}  1. Click "Get MAP_KEY"${X}`);
  console.log(`  ${D}  2. Enter your email${X}`);
  console.log(`  ${D}  3. Copy the key from the confirmation email${X}`);
  console.log('');
  const firmsKey = await ask(`  ${G}Paste your FIRMS MAP_KEY (or press Enter to skip): ${X}`);

  // ── Kilo Gateway API Key ──
  section('2/3  Kilo Gateway — AI GeoScience Assistant');
  console.log(`  The AI assistant helps geoscientists with satellite band recommendations,`);
  console.log(`  spectral indices, and processing workflows for disaster analysis.`);
  console.log(`  Without this key, a ${G}built-in knowledge engine${X} provides fallback answers.`);
  console.log('');
  console.log(`  ${C}${B}Get your free API key here:${X}`);
  console.log(`  ${B}→ https://app.kilo.ai${X}`);
  console.log(`  ${D}  1. Sign up for a free account${X}`);
  console.log(`  ${D}  2. Go to API Keys → Create new key${X}`);
  console.log(`  ${D}  3. Copy the generated key${X}`);
  console.log('');
  const kiloKey = await ask(`  ${G}Paste your Kilo API key (or press Enter to skip): ${X}`);

  // ── Port Configuration ──
  section('3/3  Server Configuration');
  const portInput = await ask(`  ${G}Port number (default 4100): ${X}`);
  const port = portInput.trim() || '4100';

  // ── Write .env file ──
  section('Creating .env');

  const envContent = [
    '# TerraMind Core v4.0 — Environment Configuration',
    `# Generated by setup wizard on ${new Date().toISOString()}`,
    '',
    '# Server',
    `PORT=${port}`,
    'HOST=0.0.0.0',
    '',
    '# NASA FIRMS (Fire Information for Resource Management System)',
    '# Get key: https://firms.modaps.eosdis.nasa.gov/api/area/',
    `FIRMS_MAP_KEY=${firmsKey.trim()}`,
    '',
    '# Cache TTL in milliseconds (default: 60s)',
    'CACHE_TTL=60000',
    '',
    '# Auto-refresh interval in milliseconds (default: 2 minutes)',
    'REFRESH_INTERVAL=120000',
    '',
    '# Kilo Gateway AI (GeoScience Assistant)',
    '# Get key: https://app.kilo.ai',
    `KILOCODE_API_KEY=${kiloKey.trim()}`,
    '',
  ].join('\n');

  writeFileSync('.env', envContent);
  console.log(`  ${G}✅ .env file created successfully${X}`);
  console.log('');

  // ── Summary ──
  console.log(`  ${B}Configuration Summary:${X}`);
  console.log(`    Port:           ${C}${port}${X}`);
  console.log(`    FIRMS:          ${firmsKey.trim() ? `${G}✅ Configured — fire detection enabled${X}` : `${Y}⬚  Skipped — fire detection disabled${X}`}`);
  console.log(`    AI Assistant:   ${kiloKey.trim() ? `${G}✅ Configured — Kilo Gateway enabled${X}` : `${Y}⬚  Skipped — using built-in engine${X}`}`);

  await installAndStart();
  rl.close();
}

async function installAndStart() {
  section('Installing Dependencies');

  const pm = detectPM();
  console.log(`  ${D}Using: ${pm}${X}`);
  console.log('');

  try {
    console.log(`  Installing packages...`);
    execSync(`${pm} install`, { stdio: 'inherit' });
    console.log('');
    console.log(`  ${G}✅ Dependencies installed successfully${X}`);
  } catch (err) {
    console.log(`  ${R}❌ Installation failed. Try running "${pm} install" manually.${X}`);
    return;
  }

  // ── Launch ──
  section('🚀 Ready to Launch');

  console.log(`  ${G}${B}TerraMind Core is ready!${X}`);
  console.log('');
  console.log(`  After starting, open your browser to:`);
  console.log('');
  console.log(`    ${B}Dashboard:${X}  http://localhost:4100`);
  console.log(`    ${B}API Docs:${X}   http://localhost:4100/api/docs`);
  console.log(`    ${B}API:${X}        http://localhost:4100/api/events`);
  console.log(`    ${B}Health:${X}     http://localhost:4100/api/health`);
  console.log('');

  const startNow = await ask(`  ${G}Start the server now? (Y/n): ${X}`);

  if (startNow.toLowerCase() !== 'n') {
    console.log('');
    console.log(`  ${C}Starting TerraMind Core... (Ctrl+C to stop)${X}`);
    console.log('');
    try {
      execSync(`${pm === 'pnpm' ? 'pnpm' : 'npm run'} dev`, { stdio: 'inherit' });
    } catch {
      // User hit Ctrl+C — clean exit
      console.log('');
      console.log(`  ${D}Server stopped.${X}`);
    }
  } else {
    console.log('');
    console.log(`  To start later, run:`);
    console.log(`    ${C}${pm === 'pnpm' ? 'pnpm' : 'npm run'} dev${X}`);
    console.log('');
  }
}

function detectPM() {
  try { execSync('pnpm --version', { stdio: 'ignore' }); return 'pnpm'; } catch {}
  try { execSync('yarn --version', { stdio: 'ignore' }); return 'yarn'; } catch {}
  return 'npm';
}

main().catch((err) => {
  console.error(`\n${R}Setup failed: ${err.message}${X}\n`);
  rl.close();
  process.exit(1);
});
